// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilqojycyxyfuwpzfabgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlscW9qeWN5eHlmdXdwemZhYmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTk2MzYsImV4cCI6MjA2NTM3NTYzNn0.VFl1F9OSbx5HBUa80AeqWkmqws6ERovB7jF1dxtqoWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);